/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package excepcionrango;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dario
 */
public class ExcepcionRango extends javax.swing.JFrame {

    /**
     * Creates new form ExcepcionRango
     */
    public ExcepcionRango() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        evaluacion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        num1 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ejercicio XII");

        evaluacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        evaluacion.setText("Evaluacion:");

        jButton1.setText("Evaluar Rango");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addComponent(evaluacion))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(evaluacion)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Obtenemos el texto del TextField num1
        String num= num1.getText();
        //Converimos a entero el texto
        int n= Integer.parseInt(num);
         //Intenta realizar el procedimiento dentro del bloque de codigo del try, si se llega a lanzar una excepcion se interrumpe
            //el procedimiento y se realiza la logica en el catch correspondiente
        try {
            //Colocamos el texto retornado del metodo evaluarRango en el label evaluacion
            evaluacion.setText(evaluarRango(n));
        } 
        //Si se dispara una excepcion de tipo RangoException se interrumpe el procedimiento en el  bloque de codigo de Try
        //y realiza el procedimiento del catch
        catch (RangoException ex) {
            //imprimimos el mensaje de la excepcion 
            evaluacion.setText(ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Metodo que evalua si un numero esta dentro del rango establecido
    //con la sentencia throws definimos las excepciones que queremos lanzar separadas por una coma
    //Ej. public String evaluarRango(int num) throws NumberFormatException, ArithmeticException{....
    public String evaluarRango(int num)throws RangoException{
        //Si el numero esta dentro del rango imprimimos retornamos Rango Correcto
        if(num>=100 && num <=150)
           return "Rango Correcto";
        //En caso contrario lanzamos una excepcion del tipo RangoException con el mensaje "Rango Incorrecto"
        else
            throw new RangoException("Rango Incorrecto");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcepcionRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcepcionRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcepcionRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcepcionRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExcepcionRango().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel evaluacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField num1;
    // End of variables declaration//GEN-END:variables
}
